<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>iCallManager.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="iCallManager.ico" LogicalName="iCallManager.ApplicationIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Tests\**\*.cs" />
    <Compile Remove="src\**\*.cs" />
    <EmbeddedResource Remove="src\**\*" />
    <None Remove="src\**\*" />
    <EmbeddedResource Remove="Tests\**\*" />
    <None Remove="Tests\**\*" />
  </ItemGroup>

  <ItemGroup>
    <COMReference Include="UIAutomationClient">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>944de083-8fb8-45cf-bcb7-c477acb2f897</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>False</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>
  
</Project>
